### ISSUE TITLE
Manifest unknown error

### ISSUE THREAD

**Issue by drmiller4** [icp4a/workflow-process-service-trial#2]
Received a manifest unknown error yesterday when attempting to run a docker-compose up command. The error occurs when attempting to pull the image below. To workaround temporarily, I changed the name of the image being pulled - dropping off the IF001.

`Pulling pc (icr.io/icp4ba/workflow-ps-trial:21.0.2-IF001)...
ERROR: manifest for icr.io/icp4ba/workflow-ps-trial:21.0.2-IF001 not found: manifest unknown: manifest unknown`

**Comment by MalekJabri** [comment]
@drmiller4 you can still pull the following container: icr.io/icp4ba/workflow-ps-trial:21.0.2 
The ifix will be provision on the icr.io soon as Information received

**Comment by drmiller4** [comment]
Yes, that is what I already did as mentioned above. fix must not be provisioned on icr.io yet.

**Comment by weijingj** [comment]
icr.io/icp4ba/workflow-ps-trial:21.0.2-IF001 has just been published. You can use it now. It recommended to use it as we have fixed several defects in IF001. Thanks. @drmiller4 @MalekJabri
